"""
BluePrint — turn part photos + one known dimension into a full engineering
drawing sheet (SVG), generated by Claude.

Endpoints:
  GET/POST /login   PIN login
  GET  /logout      clear session
  GET  /            main page (behind login)
  POST /api/generate  stream an SVG drawing sheet as NDJSON

Run locally:  python app.py   (needs APP_PIN, and either ANTHROPIC_API_KEY or
BLUEPRINT_STUB=1 for free offline testing).
"""

import json
import queue
import threading
import time
import xml.etree.ElementTree as ET
from functools import wraps

from flask import (
    Flask, request, jsonify, session, redirect, url_for,
    render_template, Response, stream_with_context,
)

import config

# ----------------------------------------------------------------------------
# Flask setup
# ----------------------------------------------------------------------------

app = Flask(__name__)
app.secret_key = config.FLASK_SECRET_KEY
app.config["MAX_CONTENT_LENGTH"] = 25 * 1024 * 1024        # 25 MB — a few photos
app.config["SESSION_COOKIE_SECURE"] = config.SESSION_COOKIE_SECURE

# Warn (don't crash) at startup if required secrets are missing, so the app
# still boots for debugging and the error is obvious in the logs.
_missing = config.missing_required()
if _missing:
    print(f"WARNING: missing env vars: {', '.join(_missing)}")


# ----------------------------------------------------------------------------
# System prompt (the instructions Claude follows to draw the sheet)
# ----------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an expert mechanical draftsperson. You produce complete engineering
drawing sheets as a single, self-contained SVG document, in the style of a
professional CAD drawing (SolidWorks / AutoCAD output).

OUTPUT RULES (hard requirements):
- Reply with ONLY one complete SVG document. Your reply must start with <svg
  and end with </svg>. No markdown fences, no commentary before or after.
- The SVG must be fully self-contained: no external images, fonts, or URLs;
  no <script>, <foreignObject>, or event-handler attributes. Use only inline
  shapes (path, line, rect, circle, ellipse, polyline, polygon, text, g,
  defs, marker) with inline presentation attributes.
- Root element: viewBox="0 0 1600 1131" (A3 landscape proportions),
  width="100%". White background rect first, black linework.

SHEET FURNITURE (draw these first):
- Double border frame with a zone grid: letters F..A top-to-bottom on both
  side margins, numbers 8..1 left-to-right on top and bottom margins, with
  tick marks, exactly like a professional CAD sheet.
- Title block in the bottom-right corner: part name, scale ratio (e.g. 1:2),
  the measurement units the user asked for, "DRAWN BY: BLUEPRINT AI".
- General notes in the top-right area when applicable (e.g. "Unspecified
  edge radius = 1mm").

VIEWS (third-angle projection):
- FRONT VIEW center-left. TOP VIEW directly above it (vertically aligned).
  RIGHT SIDE VIEW directly to its right (horizontally aligned).
  ISOMETRIC VIEW in the upper-right area of the sheet.
- If the object plausibly has internal features (bores, cavities, walls),
  add a hatched SECTION view (45-degree hatching) and label it
  "SECTION A-A (INFERRED - INTERNALS NOT VISIBLE IN PHOTOS)". Mark the
  cutting plane A-A on the front view.
- Add DETAIL views at 2:1 for small features worth magnifying, labeled
  "DETAIL B / SCALE 2:1" with a circle-and-leader callout on the parent view.
- All orthographic views share ONE scale. Label every view in uppercase text
  beneath it (e.g. "FRONT VIEW").

LINEWORK CONVENTIONS:
- Visible edges: stroke-width 2, solid. Hidden edges: stroke-width 1.2,
  stroke-dasharray "8 5". Center lines: stroke-dasharray "20 5 4 5".
- Dimension and extension lines: stroke-width 1, with small filled-triangle
  arrowheads (define once in <defs> as a <marker>). Extension lines leave a
  small gap from the part outline. Section hatching: stroke-width 0.8 lines
  at 45 degrees.

DIMENSIONING:
- The user provides exactly ONE known dimension. Anchor it exactly; derive
  every other dimension proportionally from what the photos show. Use the
  user's chosen unit for every value and round derived values sensibly for
  that unit (e.g. nearest 0.5 mm below 100 mm and nearest 1 mm above; nearest
  0.1 cm; nearest 1/16 or 0.05 in).
- Dimension the major features on the orthographic views only (never the
  isometric): overall width / height / depth, hole diameters with the
  Ø prefix, radii with R, chamfers as "1 x 45°", key feature offsets.
  Dimension text: 18px sans-serif, placed above or beside its line.
- Mark the user's given dimension with an asterisk and add the note
  "* GIVEN DIMENSION" above the title block.
- If a hole looks like a standard thread size you may annotate a guess with
  a question mark, e.g. "~M4?" — never state a thread spec as fact.

ACCURACY:
- Study all photos before drawing and reconcile the views so they are
  geometrically consistent with each other.
- If a face is not visible in any photo, infer it conservatively from
  symmetry and add a plain-text note on the sheet, e.g.
  "NOTE: BACK FACE INFERRED - NOT PHOTOGRAPHED"."""


# ----------------------------------------------------------------------------
# Auth
# ----------------------------------------------------------------------------

def login_required(view):
    """Require login. Browser pages redirect to /login; /api/* returns 401 JSON."""
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not session.get("authed"):
            if request.path.startswith("/api/"):
                return jsonify({"error": "auth required"}), 401
            return redirect(url_for("login"))
        return view(*args, **kwargs)
    return wrapped


@app.route("/login", methods=["GET", "POST"])
def login():
    if session.get("authed"):
        return redirect(url_for("home"))
    error = None
    if request.method == "POST":
        if request.form.get("pin") == config.APP_PIN and config.APP_PIN:
            session["authed"] = True
            return redirect(url_for("home"))
        error = "Wrong PIN"
    return render_template("login.html", error=error)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# ----------------------------------------------------------------------------
# Page route
# ----------------------------------------------------------------------------

@app.route("/")
@login_required
def home():
    return render_template("index.html", stub_mode=config.STUB_MODE)


# ----------------------------------------------------------------------------
# SVG safety helpers
# ----------------------------------------------------------------------------

# Element tags we always strip out — none belong in a static drawing and each
# is an XSS / external-content vector.
_REMOVE_TAGS = {"script", "foreignObject", "iframe", "embed", "object",
                "image", "audio", "video"}


def _local(tag):
    """Local tag/attribute name without its XML namespace (e.g. '{ns}svg' -> 'svg')."""
    return tag.split("}")[-1]


def extract_svg(text):
    """Return just the <svg>...</svg> slice of text, or None if not present."""
    start = text.find("<svg")
    end = text.rfind("</svg>")
    if start == -1 or end == -1:
        return None
    return text[start:end + 6]


def sanitize_svg(text):
    """Extract and clean an SVG so it's safe to inline in the browser.

    Removes disallowed elements, event-handler attributes, off-page hrefs, and
    style attributes that pull in external URLs. Returns the cleaned SVG string,
    or None if no valid SVG could be parsed.
    """
    raw = extract_svg(text)
    if raw is None:
        return None

    # Emit the SVG namespace as the default so output isn't prefixed with ns0:.
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    try:
        root = ET.fromstring(raw)
    except ET.ParseError:
        return None

    def clean(el):
        # Drop disallowed child elements; recurse into the ones we keep.
        for child in list(el):
            if _local(child.tag) in _REMOVE_TAGS:
                el.remove(child)
            else:
                clean(child)
        # Scrub dangerous attributes on this element.
        for name in list(el.attrib):
            local = _local(name).lower()
            value = el.attrib[name]
            if local.startswith("on"):                          # onclick, onload, ...
                del el.attrib[name]
            elif local == "href" and not value.strip().startswith("#"):
                del el.attrib[name]                             # covers href and xlink:href
            elif local == "style" and "url(" in value.lower():
                del el.attrib[name]

    clean(root)
    return ET.tostring(root, encoding="unicode")


# ----------------------------------------------------------------------------
# Generate endpoint
# ----------------------------------------------------------------------------

# A tiny, valid drawing-sheet-looking SVG returned in STUB_MODE so the frontend
# can be tested for free (no API call).
SAMPLE_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1600 1131" width="100%">
  <rect x="0" y="0" width="1600" height="1131" fill="white"/>
  <rect x="20" y="20" width="1560" height="1091" fill="none" stroke="black" stroke-width="3"/>
  <rect x="40" y="40" width="1520" height="1051" fill="none" stroke="black" stroke-width="1.5"/>
  <text x="60" y="70" font-family="sans-serif" font-size="20" fill="black">SAMPLE SHEET (STUB MODE)</text>
  <!-- FRONT VIEW: a simple rectangular part -->
  <rect x="500" y="450" width="300" height="200" fill="none" stroke="black" stroke-width="2"/>
  <circle cx="650" cy="550" r="40" fill="none" stroke="black" stroke-width="2"/>
  <line x1="650" y1="490" x2="650" y2="610" stroke="black" stroke-width="1" stroke-dasharray="20 5 4 5"/>
  <line x1="590" y1="550" x2="710" y2="550" stroke="black" stroke-width="1" stroke-dasharray="20 5 4 5"/>
  <text x="600" y="700" font-family="sans-serif" font-size="18" fill="black">FRONT VIEW</text>
  <!-- overall width dimension line -->
  <line x1="500" y1="720" x2="800" y2="720" stroke="black" stroke-width="1"/>
  <line x1="500" y1="650" x2="500" y2="730" stroke="black" stroke-width="1"/>
  <line x1="800" y1="650" x2="800" y2="730" stroke="black" stroke-width="1"/>
  <text x="630" y="715" font-family="sans-serif" font-size="18" fill="black">60*</text>
  <!-- overall height dimension line -->
  <line x1="850" y1="450" x2="850" y2="650" stroke="black" stroke-width="1"/>
  <line x1="800" y1="450" x2="860" y2="450" stroke="black" stroke-width="1"/>
  <line x1="800" y1="650" x2="860" y2="650" stroke="black" stroke-width="1"/>
  <text x="860" y="555" font-family="sans-serif" font-size="18" fill="black">40</text>
  <!-- title block -->
  <rect x="1180" y="960" width="380" height="130" fill="none" stroke="black" stroke-width="1.5"/>
  <text x="1195" y="995" font-family="sans-serif" font-size="18" fill="black">PART: SAMPLE BRACKET</text>
  <text x="1195" y="1025" font-family="sans-serif" font-size="16" fill="black">SCALE 1:2   UNITS mm</text>
  <text x="1195" y="1055" font-family="sans-serif" font-size="16" fill="black">DRAWN BY: BLUEPRINT AI</text>
  <text x="1195" y="945" font-family="sans-serif" font-size="14" fill="black">* GIVEN DIMENSION</text>
</svg>"""


def _ndjson(obj):
    """One NDJSON line: a JSON object followed by a newline."""
    return json.dumps(obj) + "\n"


@app.route("/api/generate", methods=["POST"])
@login_required
def api_generate():
    data = request.get_json(silent=True) or {}

    # images: 1..MAX_IMAGES non-empty base64 strings (no data: prefixes)
    images = data.get("images")
    if not isinstance(images, list) or not (1 <= len(images) <= config.MAX_IMAGES):
        return jsonify({"error": f"Provide 1 to {config.MAX_IMAGES} photo(s)."}), 400
    for b64 in images:
        if not isinstance(b64, str) or not b64.strip():
            return jsonify({"error": "Each image must be a non-empty base64 string."}), 400
        if b64.strip().startswith("data:"):
            return jsonify({"error": "Strip the 'data:...;base64,' prefix — send only the base64 data."}), 400

    dimension_label = data.get("dimension_label")
    if not isinstance(dimension_label, str) or not dimension_label.strip():
        return jsonify({"error": "A dimension label is required."}), 400
    dimension_label = dimension_label.strip()

    try:
        dimension_value = float(data.get("dimension_value"))
    except (TypeError, ValueError):
        return jsonify({"error": "dimension_value must be a number."}), 400
    if dimension_value <= 0:
        return jsonify({"error": "dimension_value must be greater than 0."}), 400

    unit = data.get("unit", "mm")
    if unit not in ("mm", "cm", "in"):
        return jsonify({"error": "unit must be 'mm', 'cm', or 'in'."}), 400

    description = data.get("description")
    if description is not None and not isinstance(description, str):
        return jsonify({"error": "description must be text."}), 400

    quality = data.get("quality", "fast")
    if quality not in ("draft", "fast", "best"):
        return jsonify({"error": "quality must be 'draft', 'fast', or 'best'."}), 400
    model = {"draft": config.MODEL_DRAFT,
             "fast": config.MODEL_FAST,
             "best": config.MODEL_BEST}[quality]

    # Real generation needs an API key. Stub mode never calls Claude.
    if not config.STUB_MODE and not config.ANTHROPIC_API_KEY:
        return jsonify({"error": "not_configured"}), 503

    def generate():
        yield _ndjson({"type": "status", "message": "Analyzing photos..."})

        # ---- Stub branch: fake progress + a canned drawing, no API call ----
        if config.STUB_MODE:
            for i in range(3):
                time.sleep(0.7)
                yield _ndjson({"type": "progress", "chars": (i + 1) * 1000})
            yield _ndjson({"type": "done", "svg": SAMPLE_SVG})
            return

        # ---- Real branch: stream from Claude ----
        import anthropic  # imported lazily so stub/local dev needn't install it

        client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
        user_text = (
            f"Object: {description or 'not described'}.\n"
            f"Known dimension: {dimension_label} = {dimension_value} {unit}.\n"
            f"Use {unit} as the unit for EVERY dimension on the sheet and state "
            f'"{unit}" as the units in the title block.\n'
            f"{len(images)} photo(s) attached. Generate the complete engineering drawing sheet now."
        )

        # The Claude stream is consumed in a background thread that pushes
        # char-counts into a queue. The response generator polls the queue with
        # a 5-second timeout, so heartbeats fire on wall-clock time even if the
        # model stream goes silent (long thinking phase) — a silent HTTP
        # response would get killed by Render's proxy.
        events_q = queue.Queue()
        outcome = {}  # "msg" on success, "exc" on failure (set by the worker)

        # Haiku 4.5 does not support adaptive thinking (the API rejects it),
        # so the thinking parameter is only sent to Sonnet/Opus.
        stream_kwargs = {}
        if quality != "draft":
            stream_kwargs["thinking"] = {"type": "adaptive"}

        def consume_stream():
            try:
                with client.messages.stream(
                    model=model,
                    max_tokens=64000,
                    **stream_kwargs,
                    system=SYSTEM_PROMPT,
                    messages=[{
                        "role": "user",
                        "content": [
                            *[{"type": "image",
                               "source": {"type": "base64", "media_type": "image/jpeg", "data": b64}}
                              for b64 in images],
                            {"type": "text", "text": user_text},
                        ],
                    }],
                ) as stream:
                    for event in stream:
                        if (getattr(event, "type", "") == "content_block_delta"
                                and getattr(event.delta, "type", None) == "text_delta"):
                            events_q.put(len(event.delta.text))
                    outcome["msg"] = stream.get_final_message()
            except Exception as exc:  # reported to the client by the generator below
                outcome["exc"] = exc
            finally:
                events_q.put(None)  # sentinel: stream finished (ok or not)

        worker = threading.Thread(target=consume_stream, daemon=True)
        worker.start()

        total_chars = 0
        last_progress_mark = 0
        while True:
            try:
                item = events_q.get(timeout=5)
            except queue.Empty:
                yield _ndjson({"type": "heartbeat"})
                continue
            if item is None:
                break
            total_chars += item
            if total_chars - last_progress_mark >= 2000:
                last_progress_mark = total_chars
                yield _ndjson({"type": "progress", "chars": total_chars})

        exc = outcome.get("exc")
        if exc is not None:
            if isinstance(exc, anthropic.AuthenticationError):
                yield _ndjson({"type": "error", "message": "Server API key is invalid."})
            elif isinstance(exc, anthropic.RateLimitError):
                yield _ndjson({"type": "error", "message": "The AI is busy — try again in a minute."})
            elif isinstance(exc, anthropic.APIStatusError):
                print(f"[BluePrint] APIStatusError {exc.status_code}: {exc.message}")
                yield _ndjson({"type": "error", "message": "Something went wrong talking to the AI — try again."})
            elif isinstance(exc, anthropic.APIConnectionError):
                yield _ndjson({"type": "error", "message": "Network error talking to the AI."})
            else:
                print(f"[BluePrint] unexpected error: {exc!r}")
                yield _ndjson({"type": "error", "message": "Something went wrong generating the drawing — try again."})
            return
        msg = outcome["msg"]

        stop = msg.stop_reason
        # flush=True so token counts appear in the log immediately (stdout is
        # block-buffered when redirected to a file, e.g. on Render)
        print(f"[BluePrint] model={model} input_tokens={msg.usage.input_tokens} "
              f"output_tokens={msg.usage.output_tokens} stop_reason={stop}", flush=True)

        if stop == "end_turn":
            # Final text comes ONLY from text blocks (skip thinking blocks).
            text = "".join(b.text for b in msg.content if b.type == "text")
            cleaned = sanitize_svg(text)
            if cleaned is None:
                print(f"[BluePrint] malformed SVG, raw prefix: {text[:200]!r}")
                yield _ndjson({"type": "error",
                               "message": "The model returned a malformed drawing — try again."})
            else:
                yield _ndjson({"type": "done", "svg": cleaned})
        elif stop == "max_tokens":
            yield _ndjson({"type": "error",
                           "message": "The drawing ran out of space — try fewer photos or a simpler object."})
        elif stop == "refusal":
            details = getattr(msg, "stop_details", None)  # may be None
            category = getattr(details, "category", None) if details else None
            print(f"[BluePrint] refusal category={category}")
            yield _ndjson({"type": "error", "message": "The model declined this request."})
        else:
            print(f"[BluePrint] unexpected stop_reason={stop}")
            yield _ndjson({"type": "error", "message": "Something went wrong generating the drawing — try again."})

    return Response(
        stream_with_context(generate()),
        mimetype="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ----------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=config.PORT, debug=config.FLASK_DEBUG)
