"""
BluePrint — turn part photos + known dimensions into a full engineering
drawing sheet (SVG), generated by Claude.

Architecture (v3, server-composed sheets): the model draws ONLY the drawing
CONTENT (orthographic views + dimensions + notes) inside a fixed content
rectangle. The server then composes the final sheet around it — border, zone
grid, title block, a COMPUTED isometric view, and code-rendered detail views
(see sheet_compose.py / iso_projection.py and ROADMAP.md "Drawing Quality
research", findings Q1-Q5).

Endpoints:
  GET/POST /login     PIN login
  GET  /logout        clear session
  GET  /              main page (behind login)
  POST /api/generate  stream a composed SVG sheet as NDJSON
  POST /api/refine    multi-turn revisions of an existing drawing
  POST /api/review    render-and-critique pass (Q5): rasterize the sheet, show
                      it back to the model, get bounded fixes

Run locally:  python app.py   (needs APP_PIN, and either ANTHROPIC_API_KEY or
BLUEPRINT_STUB=1 for free offline testing).
"""

import base64
import binascii
import json
import os
import queue
import threading
import time
import xml.etree.ElementTree as ET
from functools import wraps
from html import escape

from flask import (
    Flask, request, jsonify, session, redirect, url_for,
    render_template, Response, stream_with_context, send_from_directory,
)

import config
import sheet_compose

# ----------------------------------------------------------------------------
# Flask setup
# ----------------------------------------------------------------------------

app = Flask(__name__)
app.secret_key = config.FLASK_SECRET_KEY
app.config["MAX_CONTENT_LENGTH"] = 25 * 1024 * 1024        # 25 MB — a few photos
app.config["SESSION_COOKIE_SECURE"] = config.SESSION_COOKIE_SECURE

# Warn (don't crash) at startup if required secrets are missing, so the app
# still boots for debugging and the error is obvious in the logs.
_missing = config.missing_required()
if _missing:
    print(f"WARNING: missing env vars: {', '.join(_missing)}")


@app.url_defaults
def static_cache_bust(endpoint, values):
    """Append each static file's mtime as ?v=... so browsers (and the service
    worker's runtime cache) fetch fresh copies whenever a file changes —
    without this, cached JS/CSS can outlive a deploy and break the page."""
    if endpoint == "static" and "filename" in values:
        path = os.path.join(app.static_folder, values["filename"])
        try:
            values["v"] = int(os.path.getmtime(path))
        except OSError:
            pass


# ----------------------------------------------------------------------------
# System prompt (the instructions Claude follows to draw the sheet)
# ----------------------------------------------------------------------------

SYSTEM_PROMPT = """You are an expert mechanical draftsperson. You produce the CONTENT of an
engineering drawing sheet as a single, self-contained SVG document, in the
style of a professional CAD drawing (SolidWorks / AutoCAD output).

You do NOT draw the whole sheet. The server composes the final sheet around
your content: it draws the border, zone grid and title block, computes the
isometric view from your geometry group, and renders any detail views you
request. You draw ONLY the orthographic views, their dimensions, and general
notes, inside the content rectangle.

OUTPUT RULES (hard requirements):
- Reply with ONLY one complete SVG document. Your reply must start with <svg
  and end with </svg>. No markdown fences, no commentary before or after.
- The SVG must be fully self-contained: no external images, fonts, or URLs;
  no <script>, <foreignObject>, or event-handler attributes. Use only inline
  shapes (path, line, rect, circle, ellipse, polyline, polygon, text, g,
  defs, marker, desc) with inline presentation attributes.
- Root element: use EXACTLY the viewBox stated in the user message (the
  content area only), width="100%". Black linework, no background rect —
  the server supplies the white sheet.
- Everything you draw must fit inside that viewBox; the server hard-clips
  your content to it, so anything outside is cut off.
- Do NOT draw any of these (the server adds them): sheet border, zone grid
  or zone letters/numbers, title block, "* GIVEN DIMENSION" note, isometric
  or other pictorial views, magnified detail views.
- In multi-turn conversations, every reply — including revisions — must again be
  ONE complete content SVG following all rules here. Apply the requested change
  and keep everything else identical unless the change forces an adjustment.

VIEWS (third-angle projection):
- FRONT VIEW center-left. TOP VIEW directly above it (vertically aligned).
  RIGHT SIDE VIEW directly to its right (horizontally aligned).
- If the object plausibly has internal features (bores, cavities, walls),
  add a hatched SECTION view (45-degree hatching) and label it
  "SECTION A-A (INFERRED - INTERNALS NOT VISIBLE IN PHOTOS)". Mark the
  cutting plane A-A on the front view.
- All orthographic views share ONE scale. Label every view in uppercase text
  beneath it (e.g. "FRONT VIEW").
- General notes as plain text where space allows (e.g. "UNSPECIFIED EDGE
  RADIUS = 1MM").

DETAIL VIEW REQUESTS (optional, max 2):
- Never draw a magnified detail view yourself. Instead, when a small feature
  is worth magnifying, include ONE <desc id="detail-specs"> element whose text
  is a JSON array of at most 2 specs, e.g.
  <desc id="detail-specs">[{"view": "front", "cx": 590, "cy": 490, "r": 50,
  "scale": 2, "label": "A"}]</desc>
  where view names the source orthographic view, (cx, cy, r) is the circular
  region in YOUR content coordinates, scale is 2, and label is a single
  capital letter. The server clones that region magnified, draws the callout
  ring and leader, and places it beside the sheet. Omit the desc entirely if
  nothing needs magnifying.

MACHINE-READABLE GEOMETRY (for CAD export — load-bearing, never omit):
- Wrap the pure part linework of the three orthographic views in
  <g id="geometry" data-mm-per-unit="K"> containing exactly three subgroups:
  <g id="geo-front">, <g id="geo-top">, <g id="geo-side">. Use NO transform
  attributes on any of these groups; children stay in normal content coordinates.
- These subgroups contain ONLY part edges: visible edges, hidden edges, and
  hole circles/arcs of that view. Dimension lines, extension lines, text,
  centerlines, hatching, and section views all stay OUTSIDE the geometry
  group, drawn exactly as before.
- K = the real millimetres represented by 1 SVG unit in the orthographic views
  (e.g. a 120 mm wide part drawn 480 units wide gives data-mm-per-unit="0.25").
  All three orthographic views share one scale, so one K describes them all.
- The server also uses this group to compute the isometric view and to render
  detail views, so keep the outlines clean and closed.

SCALE REFERENCE (only when the user message reports a detected marker):
- A photo may contain a printed ArUco scale marker, annotated in the image with
  its measured pixel size. The user message then states PX-PER-MM for that
  photo. Treat that photo as metrically calibrated: derive dimensions of
  features roughly coplanar with the marker by measuring their pixel extent
  and dividing by px-per-mm, instead of estimating proportions by eye.
- The user's typed given dimensions remain authoritative for their own
  features. If the marker-derived value for one of those same features
  disagrees by more than ~5%, keep the typed value and add a plain-text note
  on the sheet about the discrepancy.

LINEWORK CONVENTIONS:
- Visible edges: stroke-width 2, solid. Hidden edges: stroke-width 1.2,
  stroke-dasharray "8 5". Center lines: stroke-dasharray "20 5 4 5".
- Dimension and extension lines: stroke-width 1, with small filled-triangle
  arrowheads (define once in <defs> as a <marker>). Extension lines leave a
  small gap from the part outline. Section hatching: stroke-width 0.8 lines
  at 45 degrees.

DIMENSIONING:
- The user provides ONE OR MORE known dimensions. ALL of them are
  authoritative: anchor each one exactly, and derive every other dimension
  proportionally from what the photos show, consistent with all the given
  values at once. Use the user's chosen unit for every value and round derived
  values sensibly for that unit (e.g. nearest 0.5 mm below 100 mm and nearest
  1 mm above; nearest 0.1 cm; nearest 1/16 or 0.05 in).
- Dimension the major features on the orthographic views: overall width /
  height / depth, hole diameters with the Ø prefix, radii with R, chamfers as
  "1 x 45°", key feature offsets. Dimension text: 18px sans-serif, placed
  above or beside its line.
- Mark EACH given dimension's value with an asterisk (e.g. "45*"). The server
  prints the "* GIVEN DIMENSION" legend on the sheet for you.
- If a hole looks like a standard thread size you may annotate a guess with
  a question mark, e.g. "~M4?" — never state a thread spec as fact.
- SNAP derived dimensions to design intent: when a derived value lands within
  ~3% of a round number, use the round number (2.97 -> 3.0; 39.4 -> 40).
  Prefer whole millimetres, then 0.5 mm. Snap hole diameters near standard
  fastener sizes to them (M3 clearance Ø3.2, M4 Ø4.5, M5 Ø5.5, M6 Ø6.6;
  tap drills M3 Ø2.5, M4 Ø3.3, M5 Ø4.2; 608 bearing seat Ø22/Ø8) and label
  the standard in brackets, e.g. "Ø4.5 (M4 CLEARANCE)". NEVER snap ANY of the
  user's given dimensions. After snapping a value, keep related dimensions
  consistent with it (positions still sum to overalls).

ACCURACY:
- Study all photos before drawing and reconcile the views so they are
  geometrically consistent with each other.
- If a face is not visible in any photo, infer it conservatively from
  symmetry and add a plain-text note on the sheet, e.g.
  "NOTE: BACK FACE INFERRED - NOT PHOTOGRAPHED".

REVIEW MODE (only when the user shows you a rendered image of your own sheet
and asks for defects):
- First line: "DEFECTS: NONE" if the render has no concrete visual defects,
  and then STOP — no SVG.
- Otherwise: "DEFECTS:" followed by up to 5 short lines, one defect each,
  each starting with "- ". Then output ONE corrected complete content SVG
  following every rule above, changing ONLY what fixes the listed defects."""


# ----------------------------------------------------------------------------
# Auth
# ----------------------------------------------------------------------------

def login_required(view):
    """Require login. Browser pages redirect to /login; /api/* returns 401 JSON."""
    @wraps(view)
    def wrapped(*args, **kwargs):
        if not session.get("authed"):
            if request.path.startswith("/api/"):
                return jsonify({"error": "auth required"}), 401
            return redirect(url_for("login"))
        return view(*args, **kwargs)
    return wrapped


@app.route("/login", methods=["GET", "POST"])
def login():
    if session.get("authed"):
        return redirect(url_for("home"))
    error = None
    if request.method == "POST":
        if request.form.get("pin") == config.APP_PIN and config.APP_PIN:
            session["authed"] = True
            return redirect(url_for("home"))
        error = "Wrong PIN"
    return render_template("login.html", error=error)


@app.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("login"))


# ----------------------------------------------------------------------------
# Page route
# ----------------------------------------------------------------------------

@app.route("/")
@login_required
def home():
    return render_template("index.html", stub_mode=config.STUB_MODE)


# ----------------------------------------------------------------------------
# SVG safety helpers
# ----------------------------------------------------------------------------

# Element tags we always strip out — none belong in a static drawing and each
# is an XSS / external-content vector.
_REMOVE_TAGS = {"script", "foreignObject", "iframe", "embed", "object",
                "image", "audio", "video"}


def _local(tag):
    """Local tag/attribute name without its XML namespace (e.g. '{ns}svg' -> 'svg')."""
    return tag.split("}")[-1]


def extract_svg(text):
    """Return just the <svg>...</svg> slice of text, or None if not present."""
    start = text.find("<svg")
    end = text.rfind("</svg>")
    if start == -1 or end == -1:
        return None
    return text[start:end + 6]


def sanitize_svg(text):
    """Extract and clean an SVG so it's safe to inline in the browser.

    Removes disallowed elements, event-handler attributes, off-page hrefs, and
    style attributes that pull in external URLs. Returns the cleaned SVG string,
    or None if no valid SVG could be parsed.
    """
    raw = extract_svg(text)
    if raw is None:
        return None

    # Emit the SVG namespace as the default so output isn't prefixed with ns0:.
    ET.register_namespace("", "http://www.w3.org/2000/svg")
    try:
        root = ET.fromstring(raw)
    except ET.ParseError:
        return None

    def clean(el):
        # Drop disallowed child elements; recurse into the ones we keep.
        for child in list(el):
            if _local(child.tag) in _REMOVE_TAGS:
                el.remove(child)
            else:
                clean(child)
        # Scrub dangerous attributes on this element.
        for name in list(el.attrib):
            local = _local(name).lower()
            value = el.attrib[name]
            if local.startswith("on"):                          # onclick, onload, ...
                del el.attrib[name]
            elif local == "href" and not value.strip().startswith("#"):
                del el.attrib[name]                             # covers href and xlink:href
            elif local == "style" and "url(" in value.lower():
                del el.attrib[name]

    clean(root)
    return ET.tostring(root, encoding="unicode")


# ----------------------------------------------------------------------------
# Generate endpoint
# ----------------------------------------------------------------------------

# A tiny, valid CONTENT fragment returned in STUB_MODE so the frontend can be
# tested for free (no API call). It goes through the REAL composer
# (sheet_compose.compose_sheet), so stub mode exercises the whole composition
# pipeline: furniture, clipping, computed isometric, and one detail view.
SAMPLE_CONTENT_SVG = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1080 840" width="100%">
  <desc id="detail-specs">[{"view": "front", "cx": 590, "cy": 490, "r": 50, "scale": 2, "label": "A"}]</desc>
  <text x="20" y="30" font-family="sans-serif" font-size="20" fill="black">SAMPLE SHEET (STUB MODE)</text>
  <!-- Part linework only (no dimensions/text) — this group is what DXF export,
       the computed isometric, and detail views all read.
       300 units wide = 60 mm given, so 1 unit = 0.2 mm. -->
  <g id="geometry" data-mm-per-unit="0.2">
    <g id="geo-front">
      <rect x="440" y="390" width="300" height="200" fill="none" stroke="black" stroke-width="2"/>
      <circle cx="590" cy="490" r="40" fill="none" stroke="black" stroke-width="2"/>
    </g>
    <g id="geo-top">
      <rect x="440" y="190" width="300" height="120" fill="none" stroke="black" stroke-width="2"/>
    </g>
    <g id="geo-side">
      <rect x="790" y="390" width="150" height="200" fill="none" stroke="black" stroke-width="2"/>
    </g>
  </g>
  <!-- FRONT VIEW centerlines (not part edges — stay outside the geometry group) -->
  <line x1="590" y1="430" x2="590" y2="550" stroke="black" stroke-width="1" stroke-dasharray="20 5 4 5"/>
  <line x1="530" y1="490" x2="650" y2="490" stroke="black" stroke-width="1" stroke-dasharray="20 5 4 5"/>
  <text x="540" y="640" font-family="sans-serif" font-size="18" fill="black">FRONT VIEW</text>
  <!-- overall width dimension line -->
  <line x1="440" y1="660" x2="740" y2="660" stroke="black" stroke-width="1"/>
  <line x1="440" y1="590" x2="440" y2="670" stroke="black" stroke-width="1"/>
  <line x1="740" y1="590" x2="740" y2="670" stroke="black" stroke-width="1"/>
  <text x="570" y="655" font-family="sans-serif" font-size="18" fill="black">60*</text>
  <!-- overall height dimension line -->
  <line x1="770" y1="390" x2="770" y2="590" stroke="black" stroke-width="1"/>
  <line x1="740" y1="390" x2="780" y2="390" stroke="black" stroke-width="1"/>
  <line x1="740" y1="590" x2="780" y2="590" stroke="black" stroke-width="1"/>
  <text x="778" y="495" font-family="sans-serif" font-size="18" fill="black">40</text>
</svg>"""


def _stub_meta():
    """meta dict for composing the stub sample sheet."""
    return {"description": "SAMPLE BRACKET", "unit": "mm"}


def _ndjson(obj):
    """One NDJSON line: a JSON object followed by a newline."""
    return json.dumps(obj) + "\n"


# ----------------------------------------------------------------------------
# Shared message building + Claude streaming (used by generate AND refine)
# ----------------------------------------------------------------------------

def build_first_user_message(images, dimensions, unit, description, scale):
    """Build the FIRST user message content (image blocks first, then one text
    block). This must be byte-identical between /api/generate, /api/refine AND
    /api/review so it forms a stable prompt-cache prefix — the cache_control
    breakpoint lives on its final text block. `dimensions` is a list of
    {"label", "value"} dicts (1..MAX_DIMENSIONS); `scale` is None or a dict with
    px_per_mm, marker_photo, and marker_size_mm from ArUco detection.
    """
    dims_text = "; ".join(f"{d['label']} = {d['value']} {unit}" for d in dimensions)
    lines = [
        f"Object: {description or 'not described'}.",
        f"Known dimensions (ALL authoritative, mark each with * on the sheet, "
        f"NEVER snap them): {dims_text}.",
        f"Use {unit} as the unit for EVERY dimension on the sheet.",
        f"Photos are attached in order as Image 1..{len(images)}.",
        f'Draw your content SVG with viewBox="{sheet_compose.CONTENT_VIEWBOX}" — '
        f"this is the content area only; the server composes the sheet border, "
        f"title block, isometric view and detail views around it.",
    ]
    if scale is not None:
        marker_size_mm = scale["marker_size_mm"]
        px_per_mm = scale["px_per_mm"]
        px = px_per_mm * marker_size_mm
        lines.append(
            f"Photo {scale['marker_photo'] + 1} contains a printed ArUco scale "
            f"marker (outlined and labeled in the image). Measured calibration "
            f"for that photo: {marker_size_mm} mm = {px} px, "
            f"i.e. {px_per_mm:.2f} px/mm."
        )
    lines.append("Generate the engineering drawing content now.")

    content = [
        {"type": "image",
         "source": {"type": "base64", "media_type": "image/jpeg", "data": b64}}
        for b64 in images
    ]
    content.append({
        "type": "text",
        "text": "\n".join(lines),
        "cache_control": {"type": "ephemeral"},  # cache prefix breakpoint
    })
    return content


def stream_drawing(model, messages, stream_kwargs, finalize):
    """Stream one model reply from Claude as NDJSON lines. Shared by generate,
    refine and review. The Claude stream is consumed in a background thread that
    pushes char-counts into a queue; this generator polls with a 5-second timeout
    so heartbeats fire on wall-clock time even during a long silent thinking phase
    (a silent HTTP response would get killed by Render's proxy).

    `finalize` is a generator function called with the model's final text; it
    yields the closing NDJSON line(s) (done or error). Generate/refine use
    make_compose_finalizer; review uses its own defect-parsing finalizer.
    """
    import anthropic  # imported lazily so stub/local dev needn't install it

    client = anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
    events_q = queue.Queue()
    outcome = {}  # "msg" on success, "exc" on failure (set by the worker)

    def consume_stream():
        try:
            with client.messages.stream(
                model=model,
                max_tokens=64000,
                **stream_kwargs,
                system=SYSTEM_PROMPT,
                messages=messages,
            ) as stream:
                for event in stream:
                    if (getattr(event, "type", "") == "content_block_delta"
                            and getattr(event.delta, "type", None) == "text_delta"):
                        events_q.put(len(event.delta.text))
                outcome["msg"] = stream.get_final_message()
        except Exception as exc:  # reported to the client by the generator below
            outcome["exc"] = exc
        finally:
            events_q.put(None)  # sentinel: stream finished (ok or not)

    worker = threading.Thread(target=consume_stream, daemon=True)
    worker.start()

    total_chars = 0
    last_progress_mark = 0
    while True:
        try:
            item = events_q.get(timeout=5)
        except queue.Empty:
            yield _ndjson({"type": "heartbeat"})
            continue
        if item is None:
            break
        total_chars += item
        if total_chars - last_progress_mark >= 2000:
            last_progress_mark = total_chars
            yield _ndjson({"type": "progress", "chars": total_chars})

    exc = outcome.get("exc")
    if exc is not None:
        if isinstance(exc, anthropic.AuthenticationError):
            yield _ndjson({"type": "error", "message": "Server API key is invalid."})
        elif isinstance(exc, anthropic.RateLimitError):
            yield _ndjson({"type": "error", "message": "The AI is busy — try again in a minute."})
        elif isinstance(exc, anthropic.APIStatusError):
            print(f"[BluePrint] APIStatusError {exc.status_code}: {exc.message}")
            yield _ndjson({"type": "error", "message": "Something went wrong talking to the AI — try again."})
        elif isinstance(exc, anthropic.APIConnectionError):
            yield _ndjson({"type": "error", "message": "Network error talking to the AI."})
        else:
            print(f"[BluePrint] unexpected error: {exc!r}")
            yield _ndjson({"type": "error", "message": "Something went wrong generating the drawing — try again."})
        return
    msg = outcome["msg"]

    stop = msg.stop_reason
    # flush=True so token counts appear in the log immediately (stdout is
    # block-buffered when redirected to a file, e.g. on Render). Cache token
    # counts are guarded — older SDKs/models may not report them.
    cache_creation = getattr(msg.usage, "cache_creation_input_tokens", 0) or 0
    cache_read = getattr(msg.usage, "cache_read_input_tokens", 0) or 0
    print(f"[BluePrint] model={model} input_tokens={msg.usage.input_tokens} "
          f"output_tokens={msg.usage.output_tokens} "
          f"cache_creation_input_tokens={cache_creation} "
          f"cache_read_input_tokens={cache_read} stop_reason={stop}", flush=True)

    if stop == "end_turn":
        # Final text comes ONLY from text blocks (skip thinking blocks).
        text = "".join(b.text for b in msg.content if b.type == "text")
        yield from finalize(text)
    elif stop == "max_tokens":
        yield _ndjson({"type": "error",
                       "message": "The drawing ran out of space — try fewer photos or a simpler object."})
    elif stop == "refusal":
        details = getattr(msg, "stop_details", None)  # may be None
        category = getattr(details, "category", None) if details else None
        print(f"[BluePrint] refusal category={category}")
        yield _ndjson({"type": "error", "message": "The model declined this request."})
    else:
        print(f"[BluePrint] unexpected stop_reason={stop}")
        yield _ndjson({"type": "error", "message": "Something went wrong generating the drawing — try again."})


def make_compose_finalizer(meta):
    """Finalizer for generate/refine: the model's reply is a CONTENT fragment;
    compose the full sheet around it, sanitize the COMPOSED sheet, and emit it.
    """
    def finalize(text):
        content = extract_svg(text)
        if content is None:
            print(f"[BluePrint] no SVG in model reply, raw prefix: {text[:200]!r}")
            yield _ndjson({"type": "error",
                           "message": "The model returned a malformed drawing — try again."})
            return
        try:
            composed = sheet_compose.compose_sheet(content, meta)
        except ValueError as exc:
            print(f"[BluePrint] compose failed: {exc}")
            yield _ndjson({"type": "error",
                           "message": "The model returned a malformed drawing — try again."})
            return
        cleaned = sanitize_svg(composed)
        if cleaned is None:
            print("[BluePrint] composed sheet failed sanitizing")
            yield _ndjson({"type": "error",
                           "message": "The model returned a malformed drawing — try again."})
            return
        yield _ndjson({"type": "done", "svg": cleaned})
    return finalize


# ----------------------------------------------------------------------------
# Input validation helpers (shared by generate + refine + review)
# ----------------------------------------------------------------------------

def _validate_images(images):
    """Validate the images list. Returns an error string, or None if OK."""
    if not isinstance(images, list) or not (1 <= len(images) <= config.MAX_IMAGES):
        return f"Provide 1 to {config.MAX_IMAGES} photo(s)."
    for b64 in images:
        if not isinstance(b64, str) or not b64.strip():
            return "Each image must be a non-empty base64 string."
        if b64.strip().startswith("data:"):
            return "Strip the 'data:...;base64,' prefix — send only the base64 data."
    return None


def _validate_scale(raw, n_images):
    """Validate the optional `scale` dict. Returns (scale, error): on success
    scale is the cleaned dict (or None if not provided) and error is None; on
    failure scale is None and error is a (response, status) tuple.
    """
    if raw is None:
        return None, None
    if not isinstance(raw, dict):
        return None, (jsonify({"error": "scale must be an object."}), 400)
    px_per_mm = raw.get("px_per_mm")
    if isinstance(px_per_mm, bool) or not isinstance(px_per_mm, (int, float)) or px_per_mm <= 0:
        return None, (jsonify({"error": "scale.px_per_mm must be a number greater than 0."}), 400)
    marker_photo = raw.get("marker_photo")
    if isinstance(marker_photo, bool) or not isinstance(marker_photo, int) or not (0 <= marker_photo < n_images):
        return None, (jsonify({"error": "scale.marker_photo is out of range."}), 400)
    marker_size_mm = raw.get("marker_size_mm")
    if isinstance(marker_size_mm, bool) or not isinstance(marker_size_mm, (int, float)) or marker_size_mm <= 0:
        return None, (jsonify({"error": "scale.marker_size_mm must be a number greater than 0."}), 400)
    return ({"px_per_mm": float(px_per_mm), "marker_photo": marker_photo,
             "marker_size_mm": marker_size_mm}, None)


def _validate_drawing_inputs(data):
    """Validate fields shared by /api/generate and /api/refine. Returns
    (parsed, error): parsed is a dict of cleaned values on success (error None),
    or None with error = (response, status) on failure.
    """
    images = data.get("images")
    err = _validate_images(images)
    if err:
        return None, (jsonify({"error": err}), 400)

    # dimensions: 1..MAX_DIMENSIONS entries of {"label": str, "value": number>0}.
    raw_dims = data.get("dimensions")
    if not isinstance(raw_dims, list) or not (1 <= len(raw_dims) <= config.MAX_DIMENSIONS):
        return None, (jsonify({"error": f"Provide 1 to {config.MAX_DIMENSIONS} dimensions."}), 400)
    dimensions = []
    for d in raw_dims:
        if not isinstance(d, dict):
            return None, (jsonify({"error": "Each dimension must be an object."}), 400)
        label = d.get("label")
        if not isinstance(label, str) or not label.strip():
            return None, (jsonify({"error": "Each dimension needs a non-empty label."}), 400)
        value = d.get("value")
        if isinstance(value, bool) or not isinstance(value, (int, float)) or value <= 0:
            return None, (jsonify({"error": "Each dimension value must be a number greater than 0."}), 400)
        dimensions.append({"label": label.strip(), "value": float(value)})

    unit = data.get("unit", "mm")
    if unit not in ("mm", "cm", "in"):
        return None, (jsonify({"error": "unit must be 'mm', 'cm', or 'in'."}), 400)

    description = data.get("description")
    if description is not None and not isinstance(description, str):
        return None, (jsonify({"error": "description must be text."}), 400)

    quality = data.get("quality", "fast")
    if quality not in ("draft", "fast", "best"):
        return None, (jsonify({"error": "quality must be 'draft', 'fast', or 'best'."}), 400)
    model = {"draft": config.MODEL_DRAFT,
             "fast": config.MODEL_FAST,
             "best": config.MODEL_BEST}[quality]

    scale, err = _validate_scale(data.get("scale"), len(images))
    if err:
        return None, err

    return ({"images": images, "dimensions": dimensions, "unit": unit,
             "description": description, "quality": quality, "model": model,
             "scale": scale}, None)


def _build_stream_kwargs(quality):
    """Assemble Claude stream options for a quality tier.

    Haiku 4.5 (draft) does not support adaptive thinking, so thinking is only
    sent to Sonnet/Opus. The Fast (Sonnet) tier also runs effort "medium" —
    output/thinking tokens are most of the cost, and medium ~matches the old
    default at lower spend. Best (Opus) keeps the default high effort.
    """
    stream_kwargs = {}
    if quality != "draft":
        stream_kwargs["thinking"] = {"type": "adaptive"}
    if quality == "fast":
        stream_kwargs["output_config"] = {"effort": "medium"}
    return stream_kwargs


# ----------------------------------------------------------------------------
# No-auth utility routes
# ----------------------------------------------------------------------------

@app.route("/healthz")
def healthz():
    """Liveness check for uptime pings — no auth."""
    return jsonify({"ok": True})


@app.route("/sw.js")
def service_worker():
    """Serve the PWA service worker from /sw.js so it can control the whole app
    scope. The file is frontend-owned and may not exist yet; if missing,
    send_from_directory returns a 404 naturally. No auth (the SW must load before
    login).
    """
    resp = send_from_directory(app.static_folder, "js/sw.js",
                               mimetype="application/javascript")
    resp.headers["Cache-Control"] = "no-cache"
    return resp


# ----------------------------------------------------------------------------
# Marker page
# ----------------------------------------------------------------------------

@app.route("/marker")
@login_required
def marker():
    return render_template("marker.html")


# ----------------------------------------------------------------------------
# Scale detection endpoint
# ----------------------------------------------------------------------------

@app.route("/api/detect-scale", methods=["POST"])
@login_required
def api_detect_scale():
    data = request.get_json(silent=True) or {}

    image = data.get("image")
    if not isinstance(image, str) or not image.strip():
        return jsonify({"error": "image must be a non-empty base64 string."}), 400
    if image.strip().startswith("data:"):
        return jsonify({"error": "Strip the 'data:...;base64,' prefix — send only the base64 data."}), 400
    try:
        jpeg_bytes = base64.b64decode(image, validate=True)
    except (binascii.Error, ValueError):
        return jsonify({"error": "image is not valid base64."}), 400

    if config.STUB_MODE:
        time.sleep(0.3)
        return jsonify({"found": True, "px_per_mm": 8.0,
                        "marker_size_mm": config.MARKER_SIZE_MM,
                        "annotated_image": image, "angle_warning": False})

    import aruco_scale  # lazy so stub/local dev needn't install OpenCV
    return jsonify(aruco_scale.detect_and_annotate(jpeg_bytes))


# ----------------------------------------------------------------------------
# Generate endpoint
# ----------------------------------------------------------------------------

@app.route("/api/generate", methods=["POST"])
@login_required
def api_generate():
    data = request.get_json(silent=True) or {}
    parsed, error = _validate_drawing_inputs(data)
    if error:
        return error

    # Real generation needs an API key. Stub mode never calls Claude.
    if not config.STUB_MODE and not config.ANTHROPIC_API_KEY:
        return jsonify({"error": "not_configured"}), 503

    quality = parsed["quality"]
    model = parsed["model"]

    meta = {"description": parsed["description"], "unit": parsed["unit"]}

    def generate():
        yield _ndjson({"type": "status", "message": "Analyzing photos..."})

        # ---- Stub branch: fake progress + the sample content run through the
        # REAL composer, so stub mode tests the whole composition pipeline ----
        if config.STUB_MODE:
            for i in range(3):
                time.sleep(0.7)
                yield _ndjson({"type": "progress", "chars": (i + 1) * 1000})
            composed = sheet_compose.compose_sheet(SAMPLE_CONTENT_SVG, _stub_meta())
            yield _ndjson({"type": "done", "svg": sanitize_svg(composed)})
            return

        # ---- Real branch: stream from Claude ----
        messages = [{
            "role": "user",
            "content": build_first_user_message(
                parsed["images"], parsed["dimensions"], parsed["unit"],
                parsed["description"], parsed["scale"]),
        }]
        yield from stream_drawing(model, messages, _build_stream_kwargs(quality),
                                  make_compose_finalizer(meta))

    return Response(
        stream_with_context(generate()),
        mimetype="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ----------------------------------------------------------------------------
# Refine endpoint (multi-turn revisions of an existing drawing)
# ----------------------------------------------------------------------------

@app.route("/api/refine", methods=["POST"])
@login_required
def api_refine():
    data = request.get_json(silent=True) or {}
    parsed, error = _validate_drawing_inputs(data)
    if error:
        return error

    # turns: 1..MAX_REFINE_TURNS prior [{instruction, svg}] entries. Each svg must
    # look like an SVG; only turn 0's instruction may be empty (it's the original
    # generate, which had no instruction).
    turns = data.get("turns")
    if not isinstance(turns, list) or not (1 <= len(turns) <= config.MAX_REFINE_TURNS):
        return jsonify({"error": f"turns must have 1 to {config.MAX_REFINE_TURNS} entries."}), 400
    for i, turn in enumerate(turns):
        if not isinstance(turn, dict):
            return jsonify({"error": "Each turn must be an object."}), 400
        svg = turn.get("svg")
        if not isinstance(svg, str) or "<svg" not in svg:
            return jsonify({"error": "Each turn must include an svg containing '<svg'."}), 400
        instr = turn.get("instruction")
        if not isinstance(instr, str):
            return jsonify({"error": "Each turn instruction must be text."}), 400
        if i > 0 and not instr.strip():
            return jsonify({"error": "Only turn 0 may have an empty instruction."}), 400

    instruction = data.get("instruction")
    if not isinstance(instruction, str) or not instruction.strip():
        return jsonify({"error": "An instruction is required."}), 400

    if not config.STUB_MODE and not config.ANTHROPIC_API_KEY:
        return jsonify({"error": "not_configured"}), 503

    quality = parsed["quality"]
    model = parsed["model"]
    meta = {"description": parsed["description"], "unit": parsed["unit"]}

    # REFINE-HISTORY DESIGN: the client stores and sends COMPOSED sheets in
    # `turns` (that's what the user sees, saves to the gallery, and re-sends —
    # one svg shape everywhere). But the model must revise what IT authored, so
    # the server extracts each turn's CONTENT fragment out of the composed sheet
    # (sheet_compose.extract_content_fragment — deterministic, so identical
    # sheets always extract to identical fragments and the prompt-cache prefix
    # stays stable across refine turns) and sends the fragments back as the
    # assistant turns. build_first_user_message stays byte-identical with
    # /api/generate, so the big image-bearing first message keeps caching.
    fragments = []
    if not config.STUB_MODE:
        for turn in turns:
            frag = sheet_compose.extract_content_fragment(turn["svg"])
            if frag is None:
                return jsonify({"error": "old_drawing",
                                "message": "This drawing predates server-composed sheets — "
                                           "generate a new drawing to refine."}), 422
            fragments.append(frag)

    def generate():
        yield _ndjson({"type": "status", "message": "Applying your changes..."})

        # ---- Stub branch: echo the instruction into the sample content, then
        # run the REAL composer so the output is a full composed sheet ----
        if config.STUB_MODE:
            for i in range(2):
                time.sleep(0.4)
                yield _ndjson({"type": "progress", "chars": (i + 1) * 1000})
            note = (f'<text x="20" y="70" font-family="sans-serif" font-size="20" '
                    f'fill="black">REFINED (STUB): {escape(instruction)}</text>')
            content = SAMPLE_CONTENT_SVG.replace("</svg>", note + "</svg>")
            composed = sheet_compose.compose_sheet(content, _stub_meta())
            yield _ndjson({"type": "done", "svg": sanitize_svg(composed)})
            return

        # ---- Real branch: rebuild the conversation and ask for a revision ----
        # user(first message) / assistant(turn0 content) / user(turn1 instr) /
        # assistant(turn1 content) / ... / user(new instruction). Turn 0's empty
        # instruction is NOT sent — it was the original generate.
        messages = [{
            "role": "user",
            "content": build_first_user_message(
                parsed["images"], parsed["dimensions"], parsed["unit"],
                parsed["description"], parsed["scale"]),
        }]
        for i, frag in enumerate(fragments):
            if i > 0:
                messages.append({"role": "user", "content": turns[i]["instruction"]})
            messages.append({"role": "assistant", "content": frag})
        messages.append({"role": "user", "content": [
            {"type": "text", "text": instruction, "cache_control": {"type": "ephemeral"}},
        ]})

        yield from stream_drawing(model, messages, _build_stream_kwargs(quality),
                                  make_compose_finalizer(meta))

    return Response(
        stream_with_context(generate()),
        mimetype="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ----------------------------------------------------------------------------
# Review endpoint (Q5: render-and-critique, single round)
# ----------------------------------------------------------------------------

def render_svg_to_png(svg_text):
    """Rasterize an SVG sheet to PNG bytes with resvg (Rust, no system deps —
    the researched safe choice for Render; cairosvg is a known deploy trap).
    resvg loads NO system fonts by itself, so we bundle DejaVu Sans in
    static/fonts and point it there — without this all dimension text would
    silently vanish from the render."""
    import resvg_py  # lazy so stub/local dev needn't install it

    font_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                            "static", "fonts")
    png = resvg_py.svg_to_bytes(
        svg_string=svg_text,
        background="#ffffff",
        skip_system_fonts=True,          # deterministic: bundled font only
        font_dirs=[font_dir],
        font_family="DejaVu Sans",
        sans_serif_family="DejaVu Sans",
        width=1600,
    )
    return bytes(png)


# The critique instruction shown to the model along with the rendered sheet.
REVIEW_INSTRUCTION = (
    "This is a render of the engineering drawing you produced for the "
    "photographed part. List up to 5 concrete visual defects (overlapping "
    "text, colliding views, missing/broken lines, elements outside the sheet, "
    "gross proportion errors vs the photo). If there are none, reply "
    "DEFECTS: NONE. Then output the corrected content SVG per the same rules, "
    "changing ONLY what fixes the listed defects."
)


def _parse_review_reply(text):
    """Split the review reply into (defects, content_svg).

    Expected shape: "DEFECTS: NONE" alone, or "DEFECTS:" + up to 5 "- ..."
    lines + one corrected content SVG. Returns ([], None) for the NONE case;
    (defects, None) means a defect list arrived without a usable SVG.
    """
    head = text.split("<svg", 1)[0]
    if "DEFECTS: NONE" in head.upper().replace("  ", " "):
        return [], None
    defects = []
    seen_marker = False
    for line in head.splitlines():
        stripped = line.strip()
        if stripped.upper().startswith("DEFECTS"):
            seen_marker = True
            continue
        if seen_marker and stripped:
            # Strip list bullets/numbers: "- x", "* x", "1. x", "2) x"
            cleaned = stripped.lstrip("-*").strip()
            if cleaned[:2].rstrip(".)").isdigit():
                cleaned = cleaned.lstrip("0123456789.)").strip()
            if cleaned:
                defects.append(cleaned)
    return defects[:5], extract_svg(text)


def make_review_finalizer(meta):
    """Finalizer for /api/review: parse the defect list + corrected content,
    compose the corrected sheet, and emit done {"svg", "defects"}.
    A clean bill of health emits done {"svg": null, "defects": []}."""
    def finalize(text):
        defects, content = _parse_review_reply(text)
        if not defects:
            yield _ndjson({"type": "done", "svg": None, "defects": []})
            return
        if content is None:
            print(f"[BluePrint] review reply had defects but no SVG: {text[:200]!r}")
            yield _ndjson({"type": "error",
                           "message": "The review reply was malformed — try again."})
            return
        try:
            composed = sheet_compose.compose_sheet(content, meta)
        except ValueError as exc:
            print(f"[BluePrint] review compose failed: {exc}")
            yield _ndjson({"type": "error",
                           "message": "The review reply was malformed — try again."})
            return
        cleaned = sanitize_svg(composed)
        if cleaned is None:
            yield _ndjson({"type": "error",
                           "message": "The review reply was malformed — try again."})
            return
        yield _ndjson({"type": "done", "svg": cleaned, "defects": defects})
    return finalize


@app.route("/api/review", methods=["POST"])
@login_required
def api_review():
    data = request.get_json(silent=True) or {}
    parsed, error = _validate_drawing_inputs(data)
    if error:
        return error

    svg = data.get("svg")
    if not isinstance(svg, str) or "<svg" not in svg:
        return jsonify({"error": "svg must be a string containing '<svg'."}), 400
    if len(svg.encode("utf-8")) > 2 * 1024 * 1024:
        return jsonify({"error": "SVG is too large (max 2 MB)."}), 413

    if not config.STUB_MODE and not config.ANTHROPIC_API_KEY:
        return jsonify({"error": "not_configured"}), 503

    quality = parsed["quality"]
    model = parsed["model"]
    meta = {"description": parsed["description"], "unit": parsed["unit"]}

    # REVIEW-INPUT DESIGN: the client sends the COMPOSED sheet it already holds
    # (same shape as refine turns — no second svg format on the wire). The model
    # sees two things: the rasterized PNG of that composed sheet (the external
    # ground truth it must critique) and, as its own prior assistant turn, the
    # CONTENT fragment extracted from the sheet — so it revises exactly what it
    # authored, and the composed-vs-content split stays invisible to the client.
    fragment = None
    if not config.STUB_MODE:
        fragment = sheet_compose.extract_content_fragment(svg)
        if fragment is None:
            return jsonify({"error": "old_drawing",
                            "message": "This drawing predates server-composed sheets — "
                                       "generate a new drawing to review."}), 422

    def generate():
        yield _ndjson({"type": "status", "message": "Reviewing the drawing..."})

        # ---- Stub branch: canned defects + the input sheet, stamped ----
        if config.STUB_MODE:
            for i in range(2):
                time.sleep(0.4)
                yield _ndjson({"type": "progress", "chars": (i + 1) * 1000})
            stamp = ('<text x="800" y="30" font-family="sans-serif" font-size="20" '
                     'fill="black" text-anchor="middle">REVIEWED (STUB)</text>')
            yield _ndjson({"type": "done",
                           "svg": svg.replace("</svg>", stamp + "</svg>"),
                           "defects": ["Dimension text overlaps the front view (stub)",
                                       "Top view not aligned with front view (stub)"]})
            return

        # ---- Real branch: rasterize, then ask the model to critique it ----
        try:
            png_b64 = base64.b64encode(render_svg_to_png(svg)).decode("ascii")
        except Exception as exc:
            print(f"[BluePrint] review rasterize failed: {exc!r}")
            yield _ndjson({"type": "error",
                           "message": "Could not render the drawing for review."})
            return

        messages = [
            {   # byte-identical first message — shares the prompt-cache prefix
                "role": "user",
                "content": build_first_user_message(
                    parsed["images"], parsed["dimensions"], parsed["unit"],
                    parsed["description"], parsed["scale"]),
            },
            {   # the model's own authored content, reconstructed
                "role": "assistant",
                "content": fragment,
            },
            {   # the critique turn: rendered sheet + first source photo + text
                "role": "user",
                "content": [
                    {"type": "image",
                     "source": {"type": "base64", "media_type": "image/png",
                                "data": png_b64}},
                    {"type": "image",
                     "source": {"type": "base64", "media_type": "image/jpeg",
                                "data": parsed["images"][0]}},
                    {"type": "text", "text": REVIEW_INSTRUCTION,
                     "cache_control": {"type": "ephemeral"}},
                ],
            },
        ]
        yield from stream_drawing(model, messages, _build_stream_kwargs(quality),
                                  make_review_finalizer(meta))

    return Response(
        stream_with_context(generate()),
        mimetype="application/x-ndjson",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no"},
    )


# ----------------------------------------------------------------------------
# DXF export endpoint (geometry only — never calls Claude)
# ----------------------------------------------------------------------------

@app.route("/api/export-dxf", methods=["POST"])
@login_required
def api_export_dxf():
    data = request.get_json(silent=True) or {}

    svg = data.get("svg")
    if not isinstance(svg, str) or not svg.strip():
        return jsonify({"error": "svg must be a non-empty string."}), 400
    if len(svg.encode("utf-8")) > 2 * 1024 * 1024:
        return jsonify({"error": "SVG is too large (max 2 MB)."}), 413

    import dxf_export  # lazy so stub/local dev needn't install ezdxf/svgelements
    try:
        dxf_bytes = dxf_export.svg_to_dxf(svg)
    except dxf_export.NoGeometryError:
        return jsonify({"error": "no_geometry",
                        "message": "This drawing predates DXF support — generate a new drawing to export DXF."}), 422
    except Exception as exc:
        print(f"[BluePrint] DXF export failed: {exc!r}")
        return jsonify({"error": "parse_error",
                        "message": "Could not turn this drawing into DXF."}), 400

    return Response(dxf_bytes, mimetype="application/dxf",
                    headers={"Content-Disposition": "attachment; filename=blueprint.dxf"})


# ----------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=config.PORT, debug=config.FLASK_DEBUG)
